# Local environment profile
spring:
  profiles:
    active: dev

# JPA Logging
logging:
  level:
    org:
      springframework:
        # sets the log level for the ORM module of Spring Framework to TRACE, allowing for detailed logging of JPA queries and transactions.
        orm.jpa: TRACE

application:
  protected-endpoints:
    - "/protected"
    - "/user"
    - "/towns"
  scheduling:
    enabled: true
    poll-building-queue: 2000